[theme]
theme = "solarized-dark"
[icons]
icons = "awesome4"

[[block]]
block = "nvidia_gpu"
interval = 1
format = " $icon NVIDIA T550 $utilization $temperature $clocks "

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "

[[block]]
block = "bluetooth"
mac = "00:18:09:92:1B:BA"
disconnected_format = ""
format = " $icon "
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good" 

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20) $play $next |}"
player = "spotify"

[[block]]
block = "memory"
format = " $icon  $mem_used /  $mem_total"
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "battery"
format = " $percentage {$time |}"
driver = "sysfs"

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z', l:fr_BE) "
short = " $icon $timestamp.datetime(f:%R) "

[[block]]
block = "sound"
step_width = 3
