theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "net"
device = "wlan0"
format = "{ssid} {signal_strength} {ip} {speed_down;K*b} {graph_down;K*b}"
interval = 5

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95


[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"
device = "/sys/class/power_supply/BAT0"

[[block]]
block = "backlight"
device = "/sys/class/backlight/amdgpu_bl0"

[[block]]
block = "time"
format = "%a %d/%m %R"
timezone = "Europe/Berlin"
interval = 60
locale = "de_DE"

[[block]]
block = "sound"
step_width = 3
